# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:35
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bizzfuzz_number',
            field=models.PositiveSmallIntegerField(default=core.models.get_random_int),
        ),
    ]
